(function(g){var window=this;'use strict';var C2=function(a){a.publish("cardstatechange",a.Fl()&&a.Up()?1:0)},D2=function(a,b){var c=g.Pa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},Scb=function(a){var b=g.sm(a);
a=g.vm(a);return new g.am(b.x,b.y,a.width,a.height)},Tcb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.rs(a,b,function(){g.ts(e);c.apply(a,arguments)},d)},G2=function(a){a=g.Ua(a);
delete E2[a];g.Fc(E2)&&F2&&F2.stop()},Vcb=function(){F2||(F2=new g.Vo(function(){Ucb()},20));
var a=F2;a.isActive()||a.start()},Ucb=function(){var a=g.Ya();
g.vc(E2,function(b){Wcb(b,a)});
g.Fc(E2)||Vcb()},H2=function(a,b,c,d){g.hp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Wcb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Xcb(a,a.progress);a.progress==1?(a.j=0,G2(a),a.onFinish(),a.Is()):a.isPlaying()&&a.sO()},Xcb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Ycb=function(a,b){g.tb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},I2=function(a,b,c,d,e){H2.call(this,b,c,d,e);
this.element=a},Zcb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
I2.call(this,a,b,c,d,e)},$cb=function(a){return Math.pow(a,3)},adb=function(a){return 3*a*a-2*a*a*a},bdb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},J2=function(a){return a.baseUrl||null},K2=function(a,b){return g.en(g.wl(a,b),function(c){return!!c})},cdb=function(a,b,c){function d(pa){var ba=pa.hovercardButton;
if(!ba)return null;ba=ba.subscribeButtonRenderer;if(!ba)return null;var R=f(ba.unsubscribedButtonText),V=f(ba.subscribedButtonText);if(ba.subscribed){var v=f(ba.subscriberCountWithUnsubscribeText);var U=f(ba.subscriberCountText)}else v=f(ba.subscriberCountText),U=f(ba.subscriberCountWithSubscribeText);var cb=null;if(pa.signinEndpoint){cb=D2(pa,"signinEndpoint","webNavigationEndpointData","url");if(!cb){var yb,Wa;cb=(Wa=g.Q((yb=ba.signInEndpoint)==null?void 0:yb.commandMetadata,g.x1))==null?void 0:
Wa.url}if(!cb)return null}return R&&(V||cb)?{subscribed:ba.subscribed,subscribeText:R,subscribeCount:v,unsubscribeText:V,unsubscribeCount:U,enabled:ba.enabled,signinUrl:cb,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var ba=[],R=pa.videoId;R&&ba.push("v="+R);(R=pa.playlistId)&&ba.push("list="+R);(pa=pa.startTimeSeconds)&&ba.push("t="+pa);return"/watch?"+ba.join("&")}}
function f(pa){if(!pa)return null;var ba=pa.simpleText;return ba?ba:pa.runs?g.wl(pa.runs,function(R){return R.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,B=null,C=null,G=null,H=null,N=null,M=null;if(h==="VIDEO")g.Q(l,g.Hx)?m=g.Q(l,g.Hx).url:(M=g.Q(l,g.jQ),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.Q(l,g.Hx)?m=g.Q(l,g.Hx).url:(M=g.Q(l,g.jQ),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=D2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?B=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((G=D2(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=D2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=D2(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:
null,W="";if(b.metadata){var fa=f(b.metadata);fa&&(W=fa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:W,callToAction:f(b.callToAction),nY:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,fG:p,playlistLength:t,channelId:u,subscribeButton:B,subscribersText:C,isSubscribe:y,targetUrl:m||null,F$:n,sessionData:X?{itct:X}:null,dfa:q,vE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:K2(b.impressionUrls||[],J2),v$:K2(b.hovercardShowUrls||[],J2),clickUrls:K2(l.loggingUrls||[],J2),visualElement:g.rw(b.trackingParams),productPrice:H,additionalFeesText:N,watchEndpoint:M||null}},ddb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:K2(a.impressionUrls||[],J2),elements:K2(a.elements||[],function(d,e){return cdb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.rw(a.trackingParams));return c},edb=function(a){g.UX.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.KO(a)||g.MO(a);this.events=new g.wE(this);g.P(this,this.events);this.events.T(this.player,g.ZC("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.$C("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.jc);this.events.T(window,"focus",this.kda);this.load();var b=g.je("STYLE");(g.ae("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.oe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},fdb=function(a){return a.player.getVideoData().Jf?"current":a.Z?"new":"current"},L2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},gdb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=ddb(f,fdb(a))));M2(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Ew;d&&(c.postParams={ad_tracking:d});if(b=g.NLa(b))if(b=g.td(b),b=g.pd(b))a.C=g.ur(b,c)},M2=function(a,b,c){c=c===void 0?!0:c;
a.player.rf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&hdb(a);c=[];d=new g.XC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.T({I:"div",S:"ytp-ce-shadow"}),g.DR(a.player,a.B.element,4),a.D=new g.Zx(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=idb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.DR(a.player,f.element,4);var h=new g.XC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);jdb(a,f,e)}else g.Ew(new g.Qs("buildEndscreenElement null",
e))}a.player.jf(c);a.jc()}},hdb=function(a){var b=g.uw(),c=g.vw();
c&&b&&a.endscreen.visualElement&&g.Uq(g.Qw)(void 0,c,b,a.endscreen.visualElement)},idb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",La:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.vE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:N2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:O2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.lp(b.title||"")},va:b.title},{I:"div",S:b.fG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={I:"div",La:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.vE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:N2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:O2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.lp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={I:"div",La:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.vE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",La:["ytp-ce-channel-title","ytp-ce-link"],W:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.lp(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",La:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:N2(b)}]};c=new g.T(c);var d=g.be(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.cp(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.AY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",La:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.vE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.lp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",La:["ytp-ce-website-goto","ytp-ce-link"],W:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:N2(b)},{I:"div",S:"ytp-ce-expanding-icon",W:kdb(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",La:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.vE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.lp(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",La:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:N2(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.cp(c.element,"ytp-ce-placeholder");return c},N2=function(a){if(a.nY)var b=a.nY.thumbnails;
return kdb(b?b[b.length-1].url:null)},kdb=function(a){return a?{style:"background-image: url("+a+")"}:{}},jdb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.cp(b.element,"ytp-ce-force-expand"),P2(a,c.id,!0)):(g.ep(b.element,"ytp-ce-force-expand"),g.ep(b.element,"ytp-ce-element-hover"),P2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){ldb(a,b,c)});
b.listen("mouseleave",function(){mdb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.cp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){ndb(a,c,m)});
b.listen("keypress",function(m){ndb(a,c,m)});
b.listen("focus",function(){ldb(a,b,c)});
b.listen("blur",function(){mdb(a,b,c)});
b.listen("touchstart",function(){ldb(a,b,c)});
var l=g.de("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.ep(b.element,"ytp-ce-element-hover");g.ep(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=m.keyCode===9&&!m.shiftKey});
d(g.de("ytp-sb-subscribe",b.element));d(g.de("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},ndb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.bp(d,"ytp-ce-element");){g.bp(d,"subscribe-label")&&odb(a,b);
if(g.bp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.bp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])mdb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.dfa==="new")odb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.td(O2(a,b.targetUrl)),c=g.pd(c),g.Ky(c,void 0,b.sessionData);else{var e=g.ZO(a.player.U())||a.player.getVideoData().Jf,f=function(){var h=O2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.$q(h);e&&n&&(n.v||n.list)?a.player.Fp(n.v,l,n.list,!1,void 0,m||void 0):g.Jy(h,l)};
odb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},O2=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.gP(a)+b}else return"";return b},ldb=function(a,b,c){g.bp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.cp(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Vo(function(){g.cp(b.element,"ytp-ce-element-hover")},200)).start():g.cp(b.element,"ytp-ce-element-hover"),Q2(a,c.v$),P2(a,c.id,!0))},mdb=function(a,b,c){g.ep(b.element,"ytp-ce-element-hover");
g.ep(b.element,"ytp-ce-force-expand");P2(a,c.id,!1)},P2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.gp(a.j[e].element,"ytp-ce-element-shadow-show",c)},Q2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||L2(a))c&&c();else{b=pdb(a,b);var e=0,f=!1,h=new g.Vo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Nu(b[a],d)}},odb=function(a,b,c){Q2(a,b.clickUrls,c);
(a=g.vw())&&b.F$&&g.$w(a,b.visualElement)},pdb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(qdb(b[d],c));return a},qdb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},rdb=function(a){return typeof a==="string"?a:""},R2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},sdb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},S2=function(a){return a.value?a.value:null},T2=function(a){if(!a)return null;
var b=g.td(rdb(a.value));b=g.pd(b);if(!b)return null;var c=R2(a.target,tdb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new sdb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},udb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},xdb=function(a){if(!a)return null;
var b=R2(a.type,vdb),c=R2(a.trigger,wdb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=T2(a?a:null);return b?new udb(b,c,a):null},ydb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},zdb=function(a,b){return g.Qb(a.action,b)},Adb=function(a,b){this.context=a;
this.j=b},Bdb=function(a){return a.customMessage?U2("div","iv-card-message",a.customMessage):""},V2=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},Cdb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(U2("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},U2=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.lp(c);return{I:a,W:b,va:c}},Ddb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.JE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.JE+");");c.dir=g.lp(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",La:b,W:c,V:d}},W2=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.vj.click,5)}},Edb=function(a,b){this.merchant=a;
this.price=b},Fdb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Gdb=function(a,b){return b?b:Fdb(a)?"current":"new"},X2=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Va=new Map;this.Xa=new Map;this.context.J.addEventListener(g.ZC("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.$C("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},Y2=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.tO(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.qb=!1});
a.context.j.listen(b,"touchmove",function(){a.qb=!0})},Hdb=function(a){var b;
return((b=g.Q(a,g.Hx))==null?0:b.url)?g.Q(a,g.Hx).url:(a=g.Q(a,g.jQ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},Z2=function(a,b,c){return{LZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
n3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
mN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Idb=function(a,b,c){X2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Cb=this.Ma=this.Hb=this.C=this.isInitialized=!1;this.cards=[];this.rb=this.Z=this.Ka=this.G=this.Ua=this.j=null;this.oa=[];this.qa=this.N=this.Gf=this.Ga=null;this.K=0;this.Da=new g.Vo(function(){},c.X.gk?4E3:3E3);
g.P(this,this.Da);this.fb=new g.Vo(function(){});
g.P(this,this.fb);this.Ba=new Adb(c,function(e,f,h,l,m,n){Y2(d,e,f,h,l,m,n)});
this.Y=new g.T({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",La:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.P(this,this.Y);this.D=this.Y.element;this.Wa=new g.Zx(this.Y,330);g.P(this,this.Wa);this.Kb=g.de("iv-drawer-header-text",this.D);this.B=g.de("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Hb&&$2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Hb=d.C)&&a3(d)});
this.Qa=new g.wE(this);g.P(this,this.Qa);this.J.addEventListener("videodatachange",this.uu.bind(this))},Jdb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a3(a)});
var c=b.headerText;g.qe(a.Kb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.rw(b.trackingParams);a.N=g.rw(b.closeTrackingParams);a.Gf=g.rw(b.iconTrackingParams)},Kdb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.eb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,vj:{},Xp:null,ek:e.trackingParams?g.rw(e.trackingParams):null,Gf:f&&f.trackingParams?g.rw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
JE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};b3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:c3(a,c,b,f),sponsored:!1,vj:Z2(f,e,f.command),Xp:f.trackingParams?g.rw(f.trackingParams):null,ek:e.trackingParams?g.rw(e.trackingParams):null,Gf:l&&l.trackingParams?g.rw(l.trackingParams):null,imageUrl:d3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.nx(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,JE:null,title:f.title?g.nx(f.title):"",customMessage:f.callToAction?g.nx(f.callToAction):"",url:g.Q(f.command,g.Hx).url?T2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.Hx).url}):null,onClickCommand:null};b3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:c3(a,c,b,e),sponsored:!1,vj:Z2(e,f,e.endpoint),Xp:e.trackingParams?g.rw(e.trackingParams):null,ek:f.trackingParams?g.rw(f.trackingParams):null,Gf:l&&l.trackingParams?g.rw(l.trackingParams):null,channelId:g.Q(e.endpoint,g.DQ).browseId,customMessage:e.customText?g.nx(e.customText):null,profileImageUrl:d3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.nx(e.channelName):"",metaInfo:[e.subscriberCountText?g.nx(e.subscriberCountText):""],url:T2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.DQ).canonicalBaseUrl?g.Q(e.endpoint,g.DQ).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.DQ).browseId}),onClickCommand:null};b3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c3(a,c,b,e),sponsored:!1,vj:Z2(e,f,e.action),Xp:e.trackingParams?g.rw(e.trackingParams):null,ek:f.trackingParams?g.rw(f.trackingParams):null,Gf:l&&l.trackingParams?g.rw(l.trackingParams):null,nI:d3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.nx(e.customMessage):null,playlistVideoCount:g.nx(e.playlistVideoCount),title:e.playlistTitle?g.nx(e.playlistTitle):"",metaInfo:[e.channelName?g.nx(e.channelName):
"",e.videoCountText?g.nx(e.videoCountText):""],url:T2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Hdb(e.action)}),onClickCommand:null};b3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c3(a,c,b,e),sponsored:!1,vj:Z2(e,f,e.action),Xp:e.trackingParams?g.rw(e.trackingParams):null,ek:f.trackingParams?g.rw(f.trackingParams):null,Gf:l&&l.trackingParams?g.rw(l.trackingParams):null,nI:d3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.nx(e.lengthString):null,customMessage:e.customMessage?g.nx(e.customMessage):null,title:e.videoTitle?g.nx(e.videoTitle):"",metaInfo:[e.channelName?g.nx(e.channelName):
"",e.viewCountText?g.nx(e.viewCountText):""],isLiveNow:!!e.badge,url:T2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Hdb(e.action)}),onClickCommand:null};b3(a,b)}}}}}a.K++},d3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},c3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Mdb=function(a,b){if(b=Ldb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Af.id),g.oe(b.dP),g.Ub(a.cards,b),a.vJ(),e3(a)},$2=function(a,b,c){if(!a.C){a.Wa.show();
a.Ua=new g.Vo(function(){g.cp(a.context.J.getRootNode(),g.D_.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Qa.T(a.B,"mousewheel",function(h){a.Da.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.vw();d&&a.Ga&&a.N&&g.Yw(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.L_||(f.L_=!0,Ndb(a.context.logger,f.Af.vj.LZ,b)),d&&g.Yw(d,[f.Af.Xp]);C2(a.J);c&&(a.G=new g.Vo(function(){a.Ka=a.Z;a.rb.focus()},330),a.G.start())}},a3=function(a){a.C&&(a.Wa.hide(),g.zs(a.Qa),g.ep(a.context.J.getRootNode(),g.D_.IV_DRAWER_OPEN),a.C=!1,C2(a.J),a.G&&a.G.stop(),a.G=new g.Vo(function(){a.Ka&&(a.Ka.focus(),a.Ka=null)},330),a.G.start())},Odb=function(a){g.dp(a.Jb(),
[g.D_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.DR(a.J,a.D,5);a.hJ();a.Z=g.de("ytp-cards-button",a.J.getRootNode());a.rb=g.de("iv-drawer-close-button",a.D);a.isInitialized=!0},Pdb=function(a){a.oa.push(g.ev("iv-teaser-shown",a.c7,a));
a.oa.push(g.ev("iv-teaser-hidden",a.aaa,a));a.oa.push(g.ev("iv-teaser-clicked",a.b7,a));a.Cb=!0},Qdb=function(a,b){var c;
return b.onClickCommand&&((c=g.Q(b.onClickCommand,g.Gab))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.qa=b,!0):!1},Rdb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.CP(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.Q(h[0],g.E2a))==null?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},b3=function(a,b){if(!Qdb(a,b)||Rdb(a,b)){var c=Sdb(a,b);
if(c){var d={Af:b,dP:c.element,L_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Cb||Pdb(a),Mdb(a,b.id),c=a.findLastIndex(d),g.$b(a.cards,c,0,d));else{a.isInitialized||Odb(a);Mdb(a,b.id);var e=a.findLastIndex(d);g.$b(a.cards,e,0,d);c.Ia(a.B,e);a.vJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,e3(a),Tdb(a,d),$2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&Udb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Udb(a,d)}),e3(a))}}},Sdb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=Ddb(b);c={I:"div",La:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?S2(b.url)||"":""},V:[V2(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[U2("h2",void 0,b.title),d]}]}]};c=new g.T(c);W2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={I:"div",La:["iv-card","iv-card-channel"],V:[{I:"a",La:["iv-click-target"],W:{href:S2(b.url)||"","data-ytid":b.channelId},V:[V2(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Bdb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},Cdb(b)]}]}]};c=new g.T(c);W2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={I:"div",La:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:S2(b.url)||""},V:[V2(b.nI,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Bdb(b),U2("h2","iv-card-primary-link",b.title),Cdb(b)]}]}]};
c=new g.T(c);W2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=b.offers.length!=0;c=["iv-card"];d="";var f=Ddb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?S2(b.url)||"":"";c={I:"div",La:c,W:{tabindex:"0"},V:[{I:"a",La:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[U2("h2",d,b.title),f]}]}]};c=new g.T(c);d=g.je("span");g.qe(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Cd(d,"adInfo");W2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",La:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",La:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:((c=b.url)==null?void 0:S2(c))||""},V:[V2(b.nI,d),{I:"div",S:"iv-card-content",V:[Bdb(b),U2("h2","iv-card-primary-link",b.title),Cdb(b),f]}]}]};c=new g.T(e);W2(a,g.ce("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Vdb=function(a){if(a.j)return a.j.Af.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.xl(a.cards,function(c){return c.Af.type==="productListing"})}return g.xl(a.cards,function(c){return c.Af.type==="productListing"})},e3=function(a){g.gp(a.J.getRootNode(),"ytp-cards-shopping-active",Vdb(a))},Udb=function(a,b){if(!g.bp(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.vw(),d=a.j?a.j.Af.Gf:a.Gf;
c&&d&&g.Zw(c,[d]);a.j=b;e3(a)}(c=a.isInitialized&&a.Jb().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Af.teaserDurationMs&&a.J.zC(!0,{teaserText:b.Af.teaserText,durationMs:b.Af.teaserDurationMs,onClickCommand:b.Af.onClickCommand});a.fb.isActive()||((!a.C||!a.Da.isActive()&&a.Ma)&&Tdb(a,b),a.fb.start(910+b.Af.teaserDurationMs))}},Tdb=function(a,b){a.Y.Fb?(b=new H2([0,
a.B.scrollTop],[0,b.dP.offsetTop],600,adb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.jx(a.Y,!0),a.B.scrollTop=b.dP.offsetTop,g.jx(a.Y,!1))},f3=function(a){return a.j&&a.j.Af?a.j.Af:a.cards[0]&&a.cards[0].Af?a.cards[0].Af:null},Ldb=function(a,b){return g.Qb(a.cards,function(c){return c.Af.id===b})},g3=function(a,b,c){X2.call(this,a,b);
this.annotation=c;this.isActive=!1},Wdb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},h3=function(a,b,c){g3.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Xdb=function(a,b){var c=c===void 0?0:c;
var d=Scb(b).width;g.qm(b,d);c=new Zcb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,$cb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.wm(b,!0)});
c.play()},$db=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
La:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",La:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.AY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ia(d));var f=a.createElement({I:"div",La:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",La:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.wm(h,!1);var l=a.createElement({I:"div",La:["branding-context-container-outer"]});l.appendChild(h);g.jm(l,"right",b.image_width+"px");g.le(a.Jb(),l);a.C=new g.Vo(function(){Ydb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Jb(),"mouseover",function(){Zdb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Jb(),"mouseout",function(){a.C.start()})}},Zdb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.vm(b);a.j||(b.style.width=g.pm(f.width,!0),c.style.width=g.pm(f.width,!0));g.jm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.jm(d,"right","1px");a.D=!0;g.wm(b,!0);a.G=new g.Vo(function(){g.cp(this.Jb(),"iv-branding-active")},0,a);
a.G.start()}},Ydb=function(a,b,c){g.ep(a.Jb(),"iv-branding-active");
a.K=new g.Vo(function(){g.wm(b,!1);a.j||(c.style.width=g.pm(0,!0))},250);
a.K.start();a.D=!1},aeb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},beb=function(a,b,c){g3.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",La:["iv-promo-contents"]});this.G=new g.Vo(function(){d.j.setAttribute("aria-hidden","true");g.wm(d.C,!1);g.wm(d.B,!0)},700,this);
g.P(this,this.G)},eeb=function(a,b,c){c.stopPropagation();
ceb(a);deb(a,b);a.j.focus()},feb=function(a){a.isCollapsed||a.Z||a.D||(g.cp(a.Jb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},ceb=function(a){a.G.stop();
a.isCollapsed&&(g.fp(a.Jb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.wm(a.B,!1),g.wm(a.C,!0))},deb=function(a,b){a.D||(a.D=g.Le(function(){geb(this);
feb(this)},b,a))},geb=function(a){a.D&&(g.Ka.clearTimeout(a.D),a.D=null)},heb=function(a){this.J=a},Ndb=function(a,b,c){b&&(c?i3(a,b.map(function(d){return g.vo(d,c)})):i3(a,b))},i3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Nu(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},ieb=function(a){g.UX.call(this,a);
var b=this;this.oa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new heb(this.player);this.D=new g.wE(this);this.G=this.N=null;this.events=new g.wE(this);this.gh=this.Y=this.j=null;this.qa=[];g.P(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.b5,this);this.subscribe("resize",this.aM,this);this.player.U().Ma.subscribe("vast_info_card_add",this.b1,this);g.P(this,this.events);this.Ba=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.T({I:"div",La:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.DR(this.player,this.B.element,4);this.B.hide();this.C=new g.T({I:"div",La:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ba);this.C.element.appendChild(a);this.Ev()&&this.load();var c=this.createElement({I:"style"});(g.ae("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.oe(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},jeb=function(a){a=a.createElement({I:"div",
La:["annotation","annotation-type-custom"]});g.wm(a,!1);return a},keb=function(a,b){b=!b.isCued()&&!g.Z(b,1024);
g.jx(a.B,b);g.jx(a.C,b)},leb=function(a,b,c){a.Z=!0;
a.G=g.ur(b,c)},meb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Qa(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(meb(a,e))}return c},qeb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Ma.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.jr(h)&&h.responseXML?h.responseXML:null)&&neb(a,h)}};
g.Ys()&&(d.onFinish=oeb(a,d.onFinish));d.postParams={ic_only:"1"};peb(d,c);a.Z=!0;g.ur(b.Va,d)}}},peb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.AJ&&(a.postParams.ic_coll=b.AJ);b.eP&&(a.postParams.ic_xml=b.eP);b.rN&&(a.postParams.ic_track=b.rN)},reb=function(a){var b=new g.T({I:"div"});
g.wm(b.element,!1);var c=new Idb(a.player,b.element,j3(a));g.P(c,b);b.Ia(a.B.element);c.XH();return c},teb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.oa=!0,seb(a,b),b.headerText&&a.gh&&(c=g.nx(b.headerText),a.gh.setAttribute("title",c))},j3=function(a){if(!a.Y){var b=new bdb(a);
g.P(a,b);var c=new g.vk(a);g.P(a,c);a.Y=new aeb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Kj)}return a.Y},neb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.vw();if(e){var f=g.uw();f&&g.Uq(g.Pw)(void 0,e,f,[g.rw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=meb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=R2(f.type,ueb),p=R2(f.style,veb),q=rdb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=xdb;if(t==null)var u=null;else if(g.Pa(t)){l=[];for(var y=g.w(t),B=y.next();!B.done;B=y.next()){var C=f(B.value);
C&&l.push(C)}u=l}else{var G=f(t);u=G?[G]:[]}e=m&&n?new ydb(m,n,p,u,r):null}else e=null}catch(fa){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=jeb(f),N=null;switch(l.type){case "branding":if(f.player.U().Dd)break;f.B.element.appendChild(H);N=new h3(H,j3(f),l);break;case "promotion":g.DR(f.player,H,4),N=new beb(H,j3(f),l)}N&&N.XH();if(f=N)g.P(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=reb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={LZ:f.impression,click:f.click,close:f.close,n3:f.teaser_impression,mN:f.teaser_click},l=e.tracking_params||{},N=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,vj:f,Xp:l.card?g.rw(l.card):null,ek:l.teaser?g.rw(l.teaser):null,Gf:l.icon?g.rw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:T2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};b3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,vj:f,
Xp:l.card?g.rw(l.card):null,ek:l.teaser?g.rw(l.teaser):null,Gf:l.icon?g.rw(l.icon):null,nI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:T2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};b3(H,c);break;case "productListing":e.signin_url&&(N=T2({target:"current",value:e.signin_url}));M=[];for(var X=e.offers||[],W=0;W<X.length;W++)M.push(new Edb(g.Ud(X[W].merchant),
g.Ud(X[W].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,vj:f,Xp:l.card?g.rw(l.card):null,ek:l.teaser?g.rw(l.teaser):null,Gf:l.icon?g.rw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,JE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:T2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),lqa:N,kqa:e.signin_title?e.signin_title:void 0,jqa:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};b3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,vj:f,Xp:l.card?g.rw(l.card):
null,ek:l.teaser?g.rw(l.teaser):null,Gf:l.icon?g.rw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,JE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:T2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};b3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,vj:f,Xp:l.card?g.rw(l.card):null,ek:l.teaser?g.rw(l.teaser):null,Gf:l.icon?g.rw(l.icon):null,nI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:T2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},b3(H,c)}}else Jdb(a.j,e);c=!0}}c&&
(C2(a.player),a.aM())},seb=function(a,b){var c=!1;
a.j||(a.j=reb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Kdb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.KQ(f)||(c=a.j,d=b.headerText?g.nx(b.headerText):"",g.qe(c.Kb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.rw(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.rw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Gf=b.icon.infoCardIconRenderer.trackingParams?g.rw(b.icon.infoCardIconRenderer.trackingParams):null,a.aM());C2(a.player)}},web=function(a,b,c,d,e){if(!a.player.U().Dd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.DQ)&&g.Q(b.navigationEndpoint,g.DQ).browseId&&f.push(new udb("openUrl","click",new sdb("/channel/"+g.Q(b.navigationEndpoint,g.DQ).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.EQ)){d.channel_id=g.Q(b.subscribeButton,g.EQ).channelId;var l;b=g.Q(b.subscribeButton,g.EQ);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.nx(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.nx(b.subscriberCountText))):(b.subscriberCountText&&(e=g.nx(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.nx(b.subscriberCountWithSubscribeText)));var m,n=((m=g.Q((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.x1))==null?void 0:m.url)||"";l={subscribeText:g.nx(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.nx(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new ydb(c,"branding","branding",f,d);l=jeb(a);a.B.element.appendChild(l);f=new h3(l,j3(a),f);f.XH();g.P(f,f);a.K[c]=f}},oeb=function(a,b){return function(){var c=g.Da.apply(0,arguments);
a.Ja()||a.qa.push(g.Oo.aj(function(){b.apply(null,g.x(c))}))}},xeb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.vR.prototype.zC=g.da(35,function(a,b){var c=g.iY(this.Ab());c&&c.zC(a,b)});
var E2={},F2=null;g.Za(H2,g.hp);g.k=H2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;G2(this);this.startTime=a=g.Ya();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.RL();this.jo("play");this.isPaused()&&this.jo("resume");this.j=1;var b=g.Ua(this);b in E2||(E2[b]=this);Vcb();Wcb(this,a);return!0};
g.k.stop=function(a){G2(this);this.j=0;a&&(this.progress=1);Xcb(this,this.progress);this.onStop();this.Is()};
g.k.pause=function(){this.isPlaying()&&(G2(this),this.j=-1,this.jo("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.jo("destroy");H2.Tf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.sO=function(){this.jo("animate")};
g.k.jo=function(a){this.dispatchEvent(new Ycb(a,this))};
g.Za(Ycb,g.tb);g.Za(I2,H2);I2.prototype.C=function(){};
I2.prototype.sO=function(){this.C();I2.Tf.sO.call(this)};
I2.prototype.Is=function(){this.C();I2.Tf.Is.call(this)};
I2.prototype.RL=function(){this.C();I2.Tf.RL.call(this)};
g.Za(Zcb,I2);Zcb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(bdb,g.O);g.k=bdb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Va)(c,d||this.B);a=g.rs(a,b,c);this.j.push(a);return a};
g.k.xG=function(a,b,c,d){c=(0,g.Va)(c,d||this.B);a=Tcb(a,b,c);this.j.push(a);return a};
g.k.Lc=function(a){g.ts(a);g.Ub(this.j,a)};
g.k.removeAll=function(){g.ts(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.O.prototype.xa.call(this)};g.z(edb,g.UX);g.k=edb.prototype;g.k.load=function(){g.UX.prototype.load.call(this);if(!L2(this)){var a=g.OLa(this.player.getVideoData());a?(a=ddb(a,fdb(this)),M2(this,a,!1)):gdb(this)}};
g.k.unload=function(){M2(this,null);this.C&&(this.C.abort(),this.C=null);g.UX.prototype.unload.call(this)};
g.k.gi=function(a,b){return L2(this)?a==="loadCustomEndscreenRenderer"?(a=ddb(b,"new"),M2(this,a),!0):null:null};
g.k.getOptions=function(){return L2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.jc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<yeb.length;f++){var h=Math.abs(b.width-yeb[f]);if(e===-1||d>=h)e=f,d=h}d=zeb[e];this.B&&g.jm(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.um(e.element,m,f);g.qm(e.element,n,p);g.fp(e.element,Aeb);m>256||f>256?g.cp(e.element,"ytp-ce-large-round"):m>96||f>96?g.cp(e.element,"ytp-ce-medium-round"):g.cp(e.element,"ytp-ce-small-round");g.fp(e.element,Beb);m=h.left+h.width/2;h=h.top+l/2;g.cp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.fp(e.element,zeb);g.cp(e.element,d);(e=g.be(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.jm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")Q2(this,this.endscreen.impressionUrls),(a=g.vw())&&this.endscreen.visualElement&&g.Xw(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.cp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.cp(b,"ytp-ce-shown");Q2(this,c.impressionUrls);(b=g.vw())&&g.Xw(b,c.visualElement);this.player.U().N&&this.player.gb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.ep(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.ep(b,"ytp-ce-shown");this.player.U().N&&this.player.gb("endscreenelementhidden",a)}};
g.k.kda=function(a){var b=this;a.target===window&&(new g.Vo(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.fp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var yeb=[346,426,470,506,570,640,853,1280,1920],zeb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Beb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Aeb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var tdb={Dha:"current",hka:"new"};var vdb={CLOSE:"close",mka:"openUrl",SUBSCRIBE:"subscribe"},wdb={mha:"click",CLOSE:"close",Eia:"hidden",Yka:"rollOut",Zka:"rollOver",mla:"shown"};ydb.prototype.Ce=function(){var a=zdb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var veb={xga:"anchored",F4:"branding",CHANNEL:"channel",Cha:"cta",Hia:"highlightText",vja:"label",PLAYLIST:"playlist",POPUP:"popup",wla:"speech",SUBSCRIBE:"subscribe",Hla:"title",VIDEO:"video",pma:"website"},ueb={F4:"branding",Zga:"card",Oha:"drawer",Gia:"highlight",Lja:"marker",Hka:"promotion",TEXT:"text",Sma:"widget"};g.z(X2,g.O);g.k=X2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.XC(a,b,{id:c,namespace:"annotations_module"});d&&this.Va.set(a,d);e&&this.Xa.set(a,e);this.context.J.jf([a],1)};
g.k.XH=function(){this.context.B.subscribe("resize",this.vJ,this)};
g.k.Jb=function(){return this.element};
g.k.tO=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.oe(this.Jb())};
g.k.vJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=S2(a);if(f){var h=Gdb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Jf||!1,n=g.$q(f||"");m&&n&&(n.v||n.list)?e.context.J.Fp(n.v,b,n.list,!1):g.Ky(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);i3(this.context.logger,c,l,d);Fdb(f)||(c=g.vw(),d=b.itct,c&&d&&g.$w(c,g.rw(d)))}};
g.k.xa=function(){this.Va.clear();this.Xa.clear();g.O.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.P(this,a);return a.element};g.z(Idb,X2);g.k=Idb.prototype;g.k.uu=function(){this.qa&&b3(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.vm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.vJ=function(){var a=this.isAvailable();g.wm(this.Jb(),a);g.gp(this.context.J.getRootNode(),g.D_.IV_DRAWER_ENABLED,a);C2(this.J)};
g.k.destroy=function(){this.J.zC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.fv(this.oa);g.zs(this.Qa);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();X2.prototype.destroy.call(this)};
g.k.hJ=function(){var a=this,b=g.de("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.Z7,this);this.context.j.listen(this.B,"touchend",function(){a.Da.start()});
this.context.j.listen(this.B,"scroll",this.w8,this);this.context.B.subscribe("onHideControls",function(){a.Ma=!0});
this.context.B.subscribe("onShowControls",function(){a.Ma=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Ma=g.bp(a.J.getRootNode(),"ytp-autohide")});
this.oa.push(g.ev("iv-button-shown",this.Z$,this));this.oa.push(g.ev("iv-button-hidden",this.Y$,this));Pdb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Rb(this.cards,function(c){return a.Af.startMs>c.Af.startMs||a.Af.startMs===c.Af.startMs&&a.Af.timestamp>=c.Af.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.Z7=function(){if(this.C){i3(this.context.logger,f3(this).vj.close);var a=g.vw();a&&this.N&&g.$w(a,this.N);a3(this)}};
g.k.w8=function(){g.gp(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.Z$=function(){var a=g.vw(),b=f3(this);b=b?b.Gf:this.Gf;a&&b&&g.Yw(a,[b])};
g.k.Y$=function(){var a=g.vw(),b=f3(this);b=b?b.Gf:this.Gf;a&&b&&g.Zw(a,[b])};
g.k.c7=function(){var a=f3(this);i3(this.context.logger,a.vj.n3);var b=g.vw();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.ek&&c.push(a.ek);a.Gf&&c.push(a.Gf);c.length>0&&g.Yw(b,c)}else g.Yw(b,[a.ek,a.Gf])};
g.k.aaa=function(){var a=g.vw(),b=f3(this);a&&b&&g.Zw(a,[b.ek])};
g.k.b7=function(a){var b=f3(this),c=g.vw();this.j?a?(a=this.context.logger,i3(a,b.vj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.ek&&g.$w(c,b.ek)):(a=this.context.logger,i3(a,b.vj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Gf&&g.$w(c,b.Gf)):(a=this.context.logger,i3(a,b.vj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Gf&&g.$w(c,this.Gf))};g.z(g3,X2);g3.prototype.XH=function(){X2.prototype.XH.call(this);Wdb(this)};
g3.prototype.show=function(){X2.prototype.show.call(this);var a=g.vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Yw(a,[g.rw(b.itct)])};
g3.prototype.hide=function(){X2.prototype.hide.call(this);var a=g.vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Zw(a,[g.rw(b.itct)])};g.z(h3,g3);
h3.prototype.Zy=function(){g.cp(this.Jb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",La:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.wm(this.B,!1);var b=this.createElement({I:"button",La:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Jb().appendChild(b);var c=this.annotation.Ce();c&&Y2(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||$db(this,
a)};
h3.prototype.show=function(){if(!this.isActive&&(g3.prototype.show.call(this),this.N||(this.Zy(),this.N=!0),g.wm(this.Jb(),!0),this.isActive=!0,this.B)){try{Xdb(this,this.B)}catch(a){}g.cp(this.context.J.getRootNode(),"ytp-branding-shown")}};
h3.prototype.hide=function(){this.isActive&&(g3.prototype.hide.call(this),g.wm(this.Jb(),!1),this.isActive=!1,g.ep(this.context.J.getRootNode(),"ytp-branding-shown"))};
h3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);g3.prototype.destroy.call(this)};g.z(beb,g3);g.k=beb.prototype;
g.k.Zy=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Jb().setAttribute("aria-hidden","true");this.Jb().setAttribute("aria-label","Promotion");this.Jb().tabIndex=0;var e=this.annotation.Ce(),f=b.image_url;if(f){var h=this.createElement({I:"div",La:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Y2(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Kd(f,S2(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",La:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",La:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&Y2(this,
this.Jb(),e,this.annotation.id,b.session_data,void 0,c)}g.cp(this.j,"iv-click-target");e&&Y2(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",La:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.cp(this.j,"iv-click-target"),e&&Y2(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",La:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){eeb(a,5E3,q)});
c.appendChild(this.B);g.wm(this.B,!1);this.context.j.listen(this.Jb(),"mouseover",this.Y9,this);this.context.j.listen(this.Jb(),"mouseout",this.X9,this);this.context.j.listen(this.Jb(),"touchend",function(q){eeb(a,5E3,q)});
this.C=this.createElement({I:"button",La:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.T9:this.S9,this);c.appendChild(this.C);g.dp(this.Jb(),d);h&&(g.le(this.Jb(),h),n&&h.appendChild(n));g.le(this.Jb(),this.N);g.le(this.Jb(),c)};
g.k.show=function(){this.isActive||(g3.prototype.show.call(this),this.Y||(this.Zy(),this.Y=!0),g.wm(this.Jb(),!0),g.Le(function(){g.ep(this.Jb(),"iv-promo-inactive")},100,this),this.Jb().removeAttribute("aria-hidden"),this.isActive=!0,geb(this),ceb(this),deb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.cp(this.Jb(),"iv-promo-inactive"),this.isActive=!1,this.Jb().setAttribute("aria-hidden","true"))};
g.k.tO=function(a,b,c,d,e,f){return this.isCollapsed?!1:g3.prototype.tO.call(this,a,b,c,d,e,f)};
g.k.Y9=function(a){this.Z=!0;eeb(this,500,a)};
g.k.X9=function(){this.Z=!1;feb(this)};
g.k.S9=function(a){a.stopPropagation();this.hide()};
g.k.T9=function(a){a.stopPropagation();geb(this);this.isCollapsed=!0;g.cp(this.Jb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();g3.prototype.destroy.call(this)};g.z(ieb,g.UX);g.k=ieb.prototype;g.k.gi=function(a,b){if(!xeb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.b1(b))&&neb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Mdb(this.j,b),C2(this.player)),!0}return null};
g.k.getOptions=function(){return xeb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ev=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.YQ(b)||g.lR(this.player.app)?!1:c===1&&!b.T1||a.Ma.get(b.videoId)||g.LQ(b)||g.MQ(b)?!0:!1};
g.k.aM=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.um(this.C.element,a.width,a.height);g.qm(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Go();a=this.j;b=b.width;g.gp(a.D,"iv-drawer-small",b<=426);g.gp(a.D,"iv-drawer-big",b>=1280)}};
g.k.b5=function(a){keb(this,a.state);g.Z(a.state,2)&&(this.Fl()&&this.Up()&&this.player.getPresentingPlayerType()!==2&&this.AC(!1),this.zC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.jr(h)&&h.responseXML?h.responseXML:null)&&(neb(b,h),g.cp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.UX.prototype.load.call(this);keb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Ys()&&(a=oeb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Ma.get(d);f&&peb(e,f);f=f&&(f.eP||f.AJ);if(!c.gw||f)c.Va?leb(this,c.Va,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.KQ(h))&&!b.oa&&teb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.DR(this.player,this.C.element,4);this.aM();(f=g.LQ(c))&&seb(this,f);(f=g.MQ(c))&&f.featuredChannel&&web(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.gh=g.de("ytp-cards-button",this.player.getRootNode());g.KQ(c)&&teb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&leb(this,b.Va,a)};
g.k.unload=function(){this.player.rf("annotations_module");for(var a=g.w(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,C2(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.K={};this.B.hide();g.UX.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.b1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?qeb(this):this.load())};
g.k.Fl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.oa};
g.k.Up=function(){return!!this.j&&this.j.C};
g.k.AC=function(a,b,c){b=b===void 0?!1:b;this.Fl();this.j&&(a?c?$2(this.j,c,b):$2(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):a3(this.j))};
g.k.zC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Ma.unsubscribe("vast_info_card_add",this.b1,this);g.ep(this.player.getRootNode(),g.D_.IV_DRAWER_OPEN);for(var a=this.qa,b=g.Oo,c=0,d=a.length;c<d;c++)b.rk(a[c]);this.qa.length=0;g.UX.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.P(this,a);return a.element};g.TX("annotations_module",ieb);g.TX("creatorendscreen",edb);})(_yt_player);
