(function(g){var window=this;'use strict';var qjb=function(a,b){a.gb("onAutonavCoundownStarted",b)},j5=function(a,b,c){g.gp(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.kh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.AP&&(b.lengthText?(e=b.lengthText||null,f=b.gy||null):b.lengthSeconds&&(e=g.uy(b.lengthSeconds),f=g.uy(b.lengthSeconds,!0)));var h=!!d;d=h&&g.yP(d).type==="RD";var l=b instanceof g.AP?b.isLivePlayback:null,m=b instanceof g.AP?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.jD("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Pl(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Jt};b instanceof g.zP&&(c.playlist_length=b.playlistLength);a.update(c)},k5=function(a){var b=a.U(),c=b.D;
g.T.call(this,{I:"a",S:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",La:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",
La:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",La:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},l5=function(a,b){b=b===void 0?!1:b;
g.T.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.T({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.P(this,this.container);this.container.Ia(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.T({I:"div",S:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",La:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.P(this,this.j);this.j.Ia(this.container.element);d||this.T(this.j.Ea("ytp-autonav-endscreen-link-container"),"click",this.xV);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.T({I:"div",S:"ytp-autonav-overlay"});g.P(this,this.overlay);this.overlay.Ia(this.container.element);this.B=new g.T({I:"div",S:"ytp-autonav-endscreen-button-container"});g.P(this,this.B);this.B.Ia(this.container.element);
this.cancelButton=new g.T({I:"button",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Cancel autoplay"},va:"Cancel"});g.P(this,this.cancelButton);this.cancelButton.Ia(this.B.element);this.cancelButton.listen("click",this.j5,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.T({I:"a",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play Now"});g.P(this,this.playButton);this.playButton.Ia(this.B.element);this.playButton.listen("click",this.xV,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&rjb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Vo(function(){sjb(c)},
500);
g.P(this,this.D);this.wV();this.T(a,"autonavvisibility",this.wV);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.i5),this.T(a,"onAutonavCoundownStarted",this.Paa))},m5=function(a){var b=a.J.Go(!0,a.J.isFullscreen());
g.gp(a.container.element,"ytp-autonav-endscreen-small-mode",a.Qg(b));g.gp(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.hN);g.gp(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Hf());g.gp(a.J.getRootNode(),"countdown-running",a.Wl());g.gp(a.container.element,"ytp-player-content",a.J.Hf());g.jm(a.overlay.element,{width:b.width+"px"});if(!a.Wl()){a.J.Hf()?tjb(a,Math.round(ujb(a)/1E3)):tjb(a);b=!!a.suggestion&&!!a.suggestion.Jt;var c=a.J.Hf()||!b;
g.gp(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.gp(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.jx(a.B,a.J.Hf());g.gp(a.element,"ytp-enable-w2w-color-transitions",vjb(a))}},sjb=function(a){var b=ujb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);tjb(a,Math.ceil((b-c)/1E3));b-c<=500&&a.Wl()?a.select(!0):a.Wl()&&a.D.start()},ujb=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.SD;return a===-1||a===void 0?8E3:a}return a.J.Yt()>=0?a.J.Yt():g.gC(a.J.U().experiments,"autoplay_time")||1E4},rjb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.I4;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},vjb=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},tjb=function(a,b){b=b===void 0?-1:b;
a=a.j.Ea("ytp-autonav-endscreen-upnext-header");g.me(a);if(b>=0){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.ke("Up next in $SECONDS".slice(0,d)));var e=g.je("span");g.ap(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.qe(e,b);a.appendChild(e);a.appendChild(g.ke("Up next in $SECONDS".slice(d+c.length)));return}}g.qe(a,"Up next")},n5=function(a,b){g.T.call(this,{I:"div",
La:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o5=function(a){g.T.call(this,{I:"div",
La:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Up Next"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ea("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Vo(this.FJ,5E3,this);this.B=0;var b=this.Ea("ytp-upnext-cancel");this.cancelButton=new g.T({I:"button",La:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},va:"Cancel"});g.P(this,this.cancelButton);this.cancelButton.listen("click",this.k5,this);this.cancelButton.Ia(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.P(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ea("ytp-upnext-autoplay-icon");this.T(b,"click",this.l5);this.api.createClientVe(b,this,115130);this.yV();this.T(a,"autonavvisibility",this.yV);this.T(a,"mdxnowautoplaying",this.Eba);this.T(a,"mdxautoplaycanceled",this.Fba);g.gp(this.element,"ytp-upnext-mobile",this.api.U().B)},wjb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.SD;return a===-1||a===void 0?8E3:a}return a.api.Yt()>=0?a.api.Yt():g.gC(a.api.U().experiments,"autoplay_time")||1E4},xjb=function(a,b){b=wjb(a,b);
var c=Math,d=c.min;var e=(0,g.S)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.Wl()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Wl()&&a.j.start()},p5=function(a){n5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.T({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",La:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.N=new g.T({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new l5(this.player);g.P(this,this.B);this.B.Ia(this.element);a.getVideoData().Uf?this.j=this.B:(this.j=new o5(a),g.DR(this.player,this.j.element,4),g.P(this,this.j));this.overlay=new g.T({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.P(this,this.overlay);this.overlay.Ia(this.element);this.D=new g.wE(this);g.P(this,this.D);g.P(this,this.table);this.table.Ia(this.element);this.table.show();g.P(this,this.N);this.N.Ia(this.table.element);this.hide()},q5=function(a){var b=a.Hf();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},r5=function(a,b){g.T.call(this,{I:"button",
La:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.N2();this.buttonType===2&&g.cp(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.N2);g.jx(this,!0)},s5=function(a,b){n5.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Ne=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new r5(a,2);g.P(this,this.watchButton);this.watchButton.Ia(this.element);this.hide()},yjb=function(a){n5.call(this,a,"subscribecard-endscreen");
this.j=new g.T({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",W:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.P(this,this.j);this.j.Ia(this.element);var b=a.getVideoData();this.subscribeButton=new g.AY("Subscribe",null,"Unsubscribe",null,!0,!1,b.wm,b.subscribed,"trailer-endscreen",null,a,!1);g.P(this,this.subscribeButton);this.subscribeButton.Ia(this.j.Ea("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Sa);this.Sa();this.hide()},t5=function(a){var b=a.U(),c=g.sE||g.CO?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.T.call(this,{I:"a",La:e,W:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",W:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",La:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",La:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.wE(this);g.P(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},u5=function(a){n5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.wE(this);g.P(this,this.B);this.K=new g.Vo(function(){g.cp(b.element,"ytp-show-tiles")},0);
g.P(this,this.K);var c=new g.T({I:"button",La:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},V:[g.qx()]});g.P(this,c);c.Ia(this.element);c.listen("click",this.p5,this);this.table=new g.gx({I:"div",S:"ytp-endscreen-content"});g.P(this,this.table);this.table.Ia(this.element);c=new g.T({I:"button",La:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},V:[g.rx()]});g.P(this,c);c.Ia(this.element);c.listen("click",this.o5,this);a.getVideoData().Uf?this.j=new l5(a,!0):this.j=
new o5(a);g.P(this,this.j);g.DR(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},v5=function(a){return g.ER(a.player)&&a.FE()&&!a.D},w5=function(a){var b=a.Hf();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},x5=function(a){n5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r5(a,1);g.P(this,this.watchButton);this.watchButton.Ia(this.element);g.r9a(a)&&(this.j=new g.d1(a),g.P(this,this.j),this.B=new g.T({I:"div",La:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},V:[this.j]}),g.P(this,this.B),this.j.Ia(this.B.element),this.B.Ia(this.element));a.createClientVe(this.element,this,156914);this.hide()},Cjb=function(a){g.UX.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.wE(this);g.P(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.fs(g.NO(c))&&d&&!g.zR(a)?(this.B=!0,this.endScreen=new s5(a,g.kR(a))):a.fd()?this.endScreen=new x5(a):zjb(a)?(this.D=!0,Ajb(this),this.j?this.endScreen=new p5(a):this.endScreen=new u5(a)):c.Eh?this.endScreen=new yjb(a):this.endScreen=new n5(a);g.P(this,this.endScreen);g.DR(a,this.endScreen.element,4);Bjb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.ZC("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.$C("endscreen"),function(e){b.onCueRangeExit(e)})},Ajb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.xm&&a.C===b.Uf)return!1;a.j=b.xm;a.C=b.Uf;return!0},zjb=function(a){a=a.U();
return a.Bd&&!a.Eh},Bjb=function(a){a.player.rf("endscreen");
var b=a.player.getVideoData();b=new g.XC(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.XC(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.jf([b,c])};
g.vR.prototype.Yt=g.da(14,function(){return this.app.Yt()});
g.G_.prototype.Yt=g.da(13,function(){return this.getVideoData().iL});
g.rR.prototype.Ts=g.da(12,function(a){this.Li().Ts(a)});
g.PY.prototype.Ts=g.da(11,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.VZ.prototype.Ts=g.da(10,function(a){this.overflowButton&&this.overflowButton.Ts(a)});
g.rR.prototype.Us=g.da(9,function(a){this.Li().Us(a)});
g.UY.prototype.Us=g.da(8,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.VZ.prototype.Us=g.da(7,function(a){this.shareButton&&this.shareButton.Us(a)});
g.rR.prototype.DC=g.da(6,function(a){this.Li().DC(a)});
g.tY.prototype.DC=g.da(5,function(a){this.fT!==a&&(this.fT=a,this.xr())});
g.rR.prototype.CC=g.da(4,function(a){this.Li().CC(a)});
g.VZ.prototype.CC=g.da(3,function(a){this.eT!==a&&(this.eT=a,this.wr())});g.z(k5,g.T);k5.prototype.select=function(){this.J.Fp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.kF||void 0)&&this.J.logClick(this.element)};
k5.prototype.onClick=function(a){g.xS(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.z(l5,g.T);g.k=l5.prototype;g.k.II=function(a){this.suggestion!==a&&(this.suggestion=a,j5(this.j,a),this.playButton.updateValue("url",this.suggestion.Pl()),m5(this))};
g.k.Wl=function(){return this.C>0};
g.k.MC=function(){this.Wl()||(this.C=Date.now(),sjb(this),qjb(this.J,ujb(this)),g.gp(this.J.getRootNode(),"countdown-running",this.Wl()))};
g.k.My=function(){this.ir();sjb(this);var a=this.j.Ea("ytp-autonav-endscreen-upnext-header");a&&g.qe(a,"Up next")};
g.k.ir=function(){this.Wl()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.ir()};
g.k.xV=function(a){g.xS(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ea("ytp-autonav-endscreen-link-container")&&(a=this.j.Ea("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.gb("innertubeCommand",this.G),this.ir()):this.select())};
g.k.j5=function(){this.J.logClick(this.cancelButton.element);g.xR(this.J,!0);this.cancelCommand&&this.J.gb("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&rjb(this,b);var c;this.cancelCommand=(c=b.E4)==null?void 0:c.command};
g.k.Paa=function(a){if(vjb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.Gy(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.Gy(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.Gy(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.Gy(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.Gy(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.Gy(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.gp(this.element,"ytp-w2w-animate",!0)}};
g.k.i5=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.gp(this.element,"ytp-w2w-animate",!1)};
g.k.wV=function(){var a=this.J.Hf();this.K&&this.Fb!==a&&g.jx(this,a);m5(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ea("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Qg=function(a){return a.width<400||a.height<459};g.z(n5,g.T);g.k=n5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.FE=function(){return!1};
g.k.Hf=function(){return!1};
g.k.l_=function(){return!1};g.z(o5,g.T);g.k=o5.prototype;g.k.FJ=function(){this.notification&&(this.D.stop(),this.Lc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.II=function(a){this.suggestion=a;j5(this,a,"hqdefault.jpg")};
g.k.yV=function(){g.jx(this,this.api.Hf());this.api.logVisibility(this.element,this.api.Hf());this.api.logVisibility(this.Ea("ytp-upnext-autoplay-icon"),this.api.Hf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Hf())};
g.k.Nba=function(){window.focus();this.FJ()};
g.k.MC=function(a){var b=this;this.Wl()||(g.gv("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.S)(),this.j=new g.Vo(function(){xjb(b,a)},25),xjb(this,a),qjb(this.api,wjb(this,a)));
g.ep(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.T.prototype.hide.call(this)};
g.k.Wl=function(){return!!this.j};
g.k.My=function(){this.ir();this.B=(0,g.S)();xjb(this);g.cp(this.element,"ytp-upnext-autoplay-paused")};
g.k.ir=function(){this.Wl()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.FJ(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.kh()}),this.C=this.T(this.notification,"click",this.Nba),this.D.start())}this.ir();this.api.nextVideo(!1,a)};
g.k.l5=function(a){!g.pe(this.cancelButton.element,a.target)&&g.xS(a,this.api)&&(this.api.Hf()&&this.api.logClick(this.Ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.k5=function(){this.api.Hf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.xR(this.api,!0)};
g.k.Eba=function(a){this.api.getPresentingPlayerType();this.show();this.MC(a)};
g.k.Fba=function(){this.api.getPresentingPlayerType();this.ir();this.hide()};
g.k.xa=function(){this.ir();this.FJ();g.T.prototype.xa.call(this)};g.z(p5,n5);g.k=p5.prototype;g.k.create=function(){n5.prototype.create.call(this);this.D.T(this.player,"appresize",this.yD);this.D.T(this.player,"onVideoAreaChange",this.yD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.zV);this.D.T(this.player,"onAutonavCancelled",this.m5);this.onVideoDataChange()};
g.k.show=function(){n5.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.xR(this.player,!1);g.ER(this.player)&&this.FE()&&!this.C?(q5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.MC():this.videoData.autonavState===3&&this.j.My()):(g.xR(this.player,!0),q5(this));this.yD()};
g.k.hide=function(){n5.prototype.hide.call(this);this.j.My();q5(this)};
g.k.yD=function(){var a=this.player.Go(!0,this.player.isFullscreen());q5(this);m5(this.B);g.gp(this.element,"ytp-autonav-cancelled-small-mode",this.Qg(a));g.gp(this.element,"ytp-autonav-cancelled-tiny-mode",this.gL(a));g.gp(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.jm(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.gp(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.kQ(this.videoData);b&&(this.j.II(b),this.j!==this.B&&this.B.II(b))}if(a&&a.length)for(b=0;b<Djb.length;++b){var c=Djb[b];if(a&&a[c]){this.videos[b]=new k5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j5(d,c));g.P(this,this.videos[b]);this.videos[b].Ia(this.N.element)}}this.yD()}};
g.k.zV=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.ir(),this.Fb&&this.yD()):(this.K=!0,this.Hf()&&(a===2?this.j.MC():a===3&&this.j.My()))};
g.k.m5=function(a){a?this.zV(1):(this.C=null,this.K=!1)};
g.k.FE=function(){return this.videoData.autonavState!==1};
g.k.Qg=function(a){return(a.width<910||a.height<459)&&!this.gL(a)&&!(a.width<=400||a.height<=360)};
g.k.gL=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Hf=function(){return this.Fb&&g.ER(this.player)&&this.FE()&&!this.C};
var Djb=[1,3,2,4];g.z(r5,g.T);g.k=r5.prototype;g.k.N2=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.yS(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.EO(b)){var c={};g.EO(b)&&g.fR(this.J,"addEmbedsConversionTrackingParams",[c]);a=g.Oi(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Fb&&this.Z)};
g.k.show=function(){g.T.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.T.prototype.hide.call(this);this.logVisibility()};
g.k.Kc=function(a){g.T.prototype.Kc.call(this,a);this.logVisibility()};g.z(s5,n5);s5.prototype.show=function(){this.player.getPlayerState()!==3&&(n5.prototype.show.call(this),this.Ne.CC(!0),this.Ne.Us(!0),this.J.U().Je||this.Ne.Ts(!0),this.J.logVisibility(this.element,!0),this.watchButton.Kc(!0))};
s5.prototype.hide=function(){n5.prototype.hide.call(this);this.Ne.CC(!1);this.Ne.Us(!1);this.Ne.Ts(!1);this.J.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(yjb,n5);yjb.prototype.Sa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.wm;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.z(t5,g.T);t5.prototype.select=function(){this.api.Fp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.kF||void 0)&&this.api.logClick(this.element)};
t5.prototype.onClick=function(a){if(g.EO(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Pl(),c={};g.AR(this.api,c);b=g.Oi(b,c);g.yS(b,this.api,a)}else g.xS(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
t5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
t5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Jf?!1:b.D};g.z(u5,n5);g.k=u5.prototype;g.k.create=function(){n5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Cr();this.B.T(this.player,"appresize",this.Cr);this.B.T(this.player,"onVideoAreaChange",this.Cr);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.ON);this.B.T(this.player,"onAutonavCancelled",this.n5);a=this.videoData.autonavState;a!==this.Y&&this.ON(a);this.B.T(this.element,"transitionend",this.cda)};
g.k.destroy=function(){g.zs(this.B);g.qb(this.stills);this.stills=[];n5.prototype.destroy.call(this);g.ep(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.FE=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Fb;n5.prototype.show.call(this);g.ep(this.element,"ytp-show-tiles");this.player.U().B?g.Xo(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.xR(this.player,!1);v5(this)?(w5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.MC():this.videoData.autonavState===3&&this.j.My()):(g.xR(this.player,!0),w5(this));a!==this.Fb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Fb;n5.prototype.hide.call(this);this.j.My();w5(this);a!==this.Fb&&this.player.logVisibility(this.element,!1)};
g.k.cda=function(a){a.target===this.element&&this.Cr()};
g.k.Cr=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.kQ(d)];if(e.length){g.cp(this.element,"ytp-endscreen-paginate");var f=this.J.Go(!0,this.J.isFullscreen());if(a=g.kR(this.J))a=a.Oh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;p>0&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&c*n-p<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;p=b*54;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.um(f,n,p);g.jm(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.II(g.kQ(this.videoData));this.j instanceof
l5&&m5(this.j);g.gp(this.element,"ytp-endscreen-takeover",v5(this));w5(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:m%2===0&&l%2===0&&(m<2&&l<2?m===0&&l===0&&(t=2):t=2),q=g.Ed(q+this.C,c),t!==0){r=this.stills[h];r||(r=new t5(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var y=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-u-4,C=Math.floor(n*(l+t)/a)-y-4;g.qm(r.element,y,u);g.um(r.element,C,B);g.jm(r.element,"transitionDelay",
(m+l)/20+"s");g.gp(r.element,"ytp-videowall-still-mini",t===1);g.gp(r.element,"ytp-videowall-still-large",t>2);t=Math.max(C,B);g.gp(r.element,"ytp-videowall-still-round-large",t>=256);g.gp(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.gp(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.bp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j5(r,q,u),g.EO(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Pl(),u={},g.fR(r.api,"addEmbedsConversionTrackingParams",[u]),t=g.Oi(t,u),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.gp(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.oe(a.element),g.pb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.kQ(a)?(this.C=0,this.videoData=a,this.Cr()):this.player.ma("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.o5=function(){this.C+=this.stills.length;this.Cr()};
g.k.p5=function(){this.C-=this.stills.length;this.Cr()};
g.k.l_=function(){return this.j.Wl()};
g.k.ON=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.ir(),this.Fb&&this.Cr()):(this.G=!0,this.Fb&&v5(this)&&(a===2?this.j.MC():a===3&&this.j.My()))};
g.k.n5=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.ON(1)}else this.D=null,this.G=!1;this.Cr()};
g.k.Hf=function(){return this.Fb&&v5(this)};g.z(x5,n5);x5.prototype.show=function(){if(this.player.getPlayerState()!==3){n5.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.gp(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.kR(this.player))==null||c.DC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Kc(!0)}};
x5.prototype.hide=function(){n5.prototype.hide.call(this);var a;(a=g.kR(this.player))==null||a.DC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(Cjb,g.UX);g.k=Cjb.prototype;g.k.Ev=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.fd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.kQ(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!zjb(this.player)||d;a=a.Pj;c=this.player.yF();return d&&!a&&!c&&!b};
g.k.Hf=function(){return this.endScreen.Hf()};
g.k.C$=function(){return this.Hf()?this.endScreen.l_():!1};
g.k.xa=function(){this.player.rf("endscreen");g.UX.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Ab().He.get("heartbeat"),d=g.kQ(a);!d||b.videoId!==d.videoId||a.VW?(this.player.Fp(b.videoId,void 0,void 0,!0,!0,b),c&&c.rL("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.UX.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.UX.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Ev()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Bjb(this);this.D&&Ajb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p5(this.player):this.endScreen=new u5(this.player),g.P(this,this.endScreen),g.DR(this.player,this.endScreen.element,4))};g.TX("endscreen",Cjb);})(_yt_player);
