(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var l=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof n&&n];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ba(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&l(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,h){this.h=f;l(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.h};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&l(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function da(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return da(this,function(b){return b})}});/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var u={};function v(){if(u!==u)throw Error("Bad secret");};function w(a){v();this.h=a}w.prototype.toString=function(){return this.h};new w("about:blank");new w("about:invalid#zClosurez");var x=[];function y(a){console.warn("A URL with content '"+a+"' was sanitized away.")}x.indexOf(y)===-1&&x.push(y);/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function z(){v()}z.prototype.toString=function(){return""};new z;var A={};function C(){if(A!==A)throw Error("SafeStyleSheet is not meant to be built directly");}C.prototype.toString=function(){return"".toString()};new C;function D(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var e=d.slice();e.push.apply(e,arguments);return a.apply(b,e)}}function ea(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}var E=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};function F(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function G(a,b){if(a.some)return a.some(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&b.call(void 0,a[c],c,a))return!0;return!1}function H(a){return Object.prototype.toString.call(a)=="[object Array]"?a:[a]};function I(a,b){return J[a]=b}var J=window._spf_state||{};window._spf_state=J;var K={};"config"in J||I("config",K);K=J.config;function L(a){var b=M();a in b&&delete b[a]}function fa(){var a=M();for(b in a)N(a[b])||delete a[b];a=M();var b=parseInt(K["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(b<=0))for(var c=0;c<b;c++){var d=Infinity,e;for(e in a)if(a[e].count<d){var f=e;d=a[e].count}delete a[f]}}function N(a){if(!(a&&"data"in a))return!1;var b=a.life;b=isNaN(b)?Infinity:b;a=a.time;return E()-a<b}function O(a){var b=parseInt(J["cache-counter"],10)||0;b++;I("cache-counter",b);a.count=b}
function M(){return"cache-storage"in J?J["cache-storage"]:I("cache-storage",{})};function P(a,b){var c=a.length-b.length;return c>=0&&a.indexOf(b,c)==c}var Q=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function R(a,b){a=a.split(b);var c=a.length==1;return[a[0],c?"":b,c?"":a.slice(1).join(b)]};function S(a){a.data&&Object.prototype.toString.call(a.data)=="[object String]"&&a.data.lastIndexOf("spf:",0)==0&&ha(a.data.substring(4))}function ha(a){var b=T[a];b&&(delete T[a],b())}function ia(a){window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)}function ja(a){window.removeEventListener?window.removeEventListener("message",a,!1):window.detachEvent&&window.detachEvent("onmessage",a)}
var ka=function(){function a(){b=!1}if(!window.postMessage)return!1;var b=!0;ia(a);window.postMessage("","*");ja(a);return b}(),T={};"async-defers"in J||I("async-defers",T);T=J["async-defers"];ka&&("async-listener"in J&&ja(J["async-listener"]),ia(S),I("async-listener",S));var la={};"ps-s"in J||I("ps-s",la);la=J["ps-s"];function U(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,username:b.username,password:b.password};a.origin=a.protocol+"//"+a.host;a.pathname&&a.pathname[0]=="/"||(a.pathname="/"+a.pathname);return a}function ma(a){a=U(a);return R(a.href,"#")[0]};/*

 SPF
 (c) 2012-2017 Google Inc.
 https://ajax.googleapis.com/ajax/libs/spf/2.4.0/LICENSE
*/
var na={},oa={},pa={};"rsrc-s"in J||I("rsrc-s",na);na=J["rsrc-s"];"rsrc-n"in J||I("rsrc-n",oa);oa=J["rsrc-n"];"rsrc-u"in J||I("rsrc-u",pa);pa=J["rsrc-u"];var qa={};"js-d"in J||I("js-d",qa);qa=J["js-d"];var ra={};"js-u"in J||I("js-u",ra);ra=J["js-u"];/*

 Copyright 2012-2017 Google Inc. All Rights Reserved.
 Use of this source code is governed by The MIT License.
 SPDX-License-Identifier: MIT
*/
function sa(a,b,c){if(b){b=[];var d=0;c&&(a+="\r\n");var e=a.indexOf("[\r\n",d);for(e>-1&&(d=e+3);(e=a.indexOf(",\r\n",d))>-1;){var f=Q(a.substring(d,e));d=e+3;f&&b.push(JSON.parse(f))}e=a.indexOf("]\r\n",d);e>-1&&(f=Q(a.substring(d,e)),d=e+3,f&&b.push(JSON.parse(f)));f="";a.length>d&&(f=a.substring(d),c&&P(f,"\r\n")&&(f=f.substring(0,f.length-2)));b=V(b);return{m:b,g:f}}a=JSON.parse(a);b=V(H(a));return{m:b,g:""}}
function V(a){var b=H(a);F(b,function(c){if(c){c.head&&(c.head=W(c.head));if(c.body)for(var d in c.body)c.body[d]=W(c.body[d]);c.foot&&(c.foot=W(c.foot))}});return a}
function W(a){var b=new ta;if(!a)return b;if(Object.prototype.toString.call(a)!="[object String]")return a.scripts&&F(a.scripts,function(c){b.scripts.push({url:c.url||"",text:c.text||"",name:c.name||"",async:c.async||!1})}),a.styles&&F(a.styles,function(c){b.styles.push({url:c.url||"",text:c.text||"",name:c.name||""})}),a.links&&F(a.links,function(c){c.rel=="spf-preconnect"&&b.links.push({url:c.url||"",rel:c.rel||""})}),b.html=a.html||"",b;a=a.replace(ua,function(c,d,e,f){if(d=="script"){d=(d=e.match(X))?
d[1]:"";var h=e.match(va);h=h?h[1]:"";var k=wa.test(e);e=xa.exec(e);return(e=!e||e[1].indexOf("/javascript")!=-1||e[1].indexOf("/x-javascript")!=-1||e[1].indexOf("/ecmascript")!=-1)?(b.scripts.push({url:h,text:f,name:d,async:k}),""):c}return d=="style"&&(d=(d=e.match(X))?d[1]:"",e=xa.exec(e),e=!e||e[1].indexOf("text/css")!=-1)?(b.styles.push({url:"",text:f,name:d}),""):c});a=a.replace(ya,function(c,d){var e=d.match(za);e=e?e[1]:"";return e=="stylesheet"?(e=(e=d.match(X))?e[1]:"",d=(d=d.match(Aa))?
d[1]:"",b.styles.push({url:d,text:"",name:e}),""):e=="spf-preconnect"?(d=(d=d.match(Aa))?d[1]:"",b.links.push({url:d,rel:e}),""):c});b.html=a;return b}function ta(){this.html="";this.scripts=[];this.styles=[];this.links=[]}(function(){var a=document.createElement("div");return"transition"in a.style?!0:G(["webkit","Moz","Ms","O","Khtml"],function(b){return b+"Transition"in a.style})})();
var ya=/\x3clink([\s\S]*?)\x3e/ig,ua=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,wa=/(?:\s|^)async(?:\s|=|$)/i,Aa=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,X=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,za=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,va=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i,xa=/(?:\s|^)type\s*=\s*["']([^"']+)["']/i;function Ba(a,b,c,d){var e=d||{},f=!1,h=0,k,g=new XMLHttpRequest;g.open(a,b,!0);g.timing={};var m=g.abort;g.abort=function(){clearTimeout(k);g.onreadystatechange=null;m.call(g)};g.onreadystatechange=function(){var q=g.timing;if(g.readyState==2){q.responseStart=q.responseStart||E();if(g.responseType=="json")f=!1;else if(K["assume-all-json-requests-chunked"]||(g.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked")>-1)f=!0;else{q=g.getResponseHeader("X-Firefox-Spdy");var B=window.chrome&&
chrome.loadTimes&&chrome.loadTimes();B=B&&B.wasFetchedViaSpdy;f=!(!q&&!B)}e.u&&e.u(g)}else g.readyState==3?f&&e.l&&(q=g.responseText.substring(h),h=g.responseText.length,e.l(g,q)):g.readyState==4&&(q.responseEnd=q.responseEnd||E(),window.performance&&window.performance.getEntriesByName&&(g.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&e.l&&g.responseText.length>h&&(q=g.responseText.substring(h),h=g.responseText.length,e.l(g,q)),clearTimeout(k),e.s&&e.s(g))};"responseType"in g&&e.responseType==
"json"&&(g.responseType="json");e.withCredentials&&(g.withCredentials=e.withCredentials);d="FormData"in window&&c instanceof FormData;a=a=="POST"&&!d;if(e.headers)for(var t in e.headers)g.setRequestHeader(t,e.headers[t]),"content-type"==t.toLowerCase()&&(a=!1);a&&g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");e.C>0&&(k=setTimeout(function(){g.abort();e.A&&e.A(g)},e.C));g.timing.fetchStart=E();g.send(c);return g};function Ca(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=E();b.type&&b.type.lastIndexOf("navigate",0)==0&&(c.navigationStart=c.startTime,K["cache-unified"]||(L(d),f=!0));b.j&&e.type=="multipart"&&F(e.parts,function(h){h.timing||(h.timing={});h.timing.spfCached=!!c.spfCached;h.timing.spfPrefetched=!!c.spfPrefetched;b.j(a,h)});Da(a,b,c,e,f)}function Ea(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.o=a.toLowerCase().indexOf("multipart")!=-1}
function Fa(a,b,c,d,e,f,h){if(d.o){f=d.g+f;try{var k=sa(f,!0,h)}catch(g){e.abort();b.i&&b.i(a,g,e);return}b.j&&F(k.m,function(g){g.timing||(g.timing={});g.timing.spfCached=!!c.spfCached;g.timing.spfPrefetched=!!c.spfPrefetched;b.j(a,g)});d.h=d.h.concat(k.m);d.g=k.g}}
function Ga(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if(b.type=="load")for(var h in e.resourceTiming)c[h]=e.resourceTiming[h];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+e.resourceTiming.startTime>=c.startTime))for(var k in e.resourceTiming)h=e.resourceTiming[k],h!==void 0&&(P(k,"Start")||P(k,"End")||k=="startTime")&&(c[k]=f+Math.round(h));b.type!="load"&&(c.navigationStart=c.startTime);d.h.length&&
(d.g=Q(d.g),d.g&&Fa(a,b,c,d,e,"",!0));if(e.responseType=="json"){if(!e.response){b.i&&b.i(a,Error("JSON response parsing failed"),e);return}var g=V(H(e.response))}else try{g=sa(e.responseText).m}catch(t){b.i&&b.i(a,t,e);return}if(b.j&&g.length>1)for(d=d.h.length;d<g.length;d++)e=g[d],e.timing||(e.timing={}),e.timing.spfCached=!!c.spfCached,e.timing.spfPrefetched=!!c.spfPrefetched,b.j(a,e);if(g.length>1){var m;F(g,function(t){t.cacheType&&(m=t.cacheType)});g={parts:g,type:"multipart"};m&&(g.cacheType=
m)}else g=g.length==1?g[0]:{};Da(a,b,c,g,!0)}function Da(a,b,c,d,e){if(e&&b.method!="POST"&&(e=Ha(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},h=parseInt(K["cache-lifetime"],10),k=parseInt(K["cache-max"],10);h<=0||k<=0||(k=M(),f={data:f,life:h,time:E(),count:0},O(f),k[e]=f,setTimeout(fa,1E3))}d.timing=c;b.v&&b.v(a,d)}
function Ha(a,b,c,d,e){a=ma(a);var f;K["cache-unified"]?f=a:d=="navigate-back"||d=="navigate-forward"?f="history "+a:d=="navigate"?f=(e?"history ":"prefetch ")+a:d=="prefetch"&&(f=e?"prefetch "+a:"");b&&c=="url"?f+=" previous "+b:b&&c=="path"&&(f+=" previous "+U(b).pathname);return f||""}
function Ia(a,b){var c=[];b&&(c.push(a+" previous "+b),c.push(a+" previous "+U(b).pathname));c.push(a);var d=null;G(c,function(e){a:{var f=M();if(e in f){f=f[e];if(N(f)){O(f);f=f.data;break a}L(e)}f=void 0}f&&(d={key:e,response:f.response,type:f.type});return!!f});return d}function Ja(){this.o=!1;this.g="";this.h=[]};function Y(a,b){if(a){var c=Array.prototype.slice.call(arguments);c[0]=a;c=ea.apply(null,c)}return c!==!1};function Ka(a,b,c,d){Y((a||{}).onError,{url:b,err:c,xhr:d})}function La(a,b,c){Y((a||{}).onPartProcess,{url:b,part:c})&&Y((a||{}).onPartDone,{url:b,part:c})}function Ma(a,b,c){var d;(d=c.type=="multipart")||(d=Y((a||{}).onProcess,{url:b,response:c}));d&&Y((a||{}).onDone,{url:b,response:c})}
var Na={request:function(a,b){b=b||{};b={method:b.method,headers:b.experimental_headers,j:D(La,null,b),i:D(Ka,null,b),v:D(Ma,null,b),D:b.postData,type:"",current:window.location.href,B:window.location.href};b.method=((b.method||"GET")+"").toUpperCase();b.type=b.type||"request";var c=a,d=K["url-identifier"]||"";if(d){d=d.replace("__type__",b.type||"");var e=R(c,"#"),f=R(e[0],"?");c=f[0];var h=f[1];f=f[2];var k=e[1];e=e[2];if(d.lastIndexOf("?",0)==0)h&&(d=d.replace("?","&")),f+=d;else{if(d.lastIndexOf(".",
0)==0)if(P(c,"/"))d="index"+d;else{var g=c.lastIndexOf(".");g>-1&&(c=c.substring(0,g))}else P(c,"/")&&d.lastIndexOf("/",0)==0&&(d=d.substring(1));c+=d}c=c+h+f+k+e}d=ma(c);c={};c.spfUrl=d;c.startTime=E();c.fetchStart=c.startTime;h=Ha(a,b.current,null,b.type,!1);h=Ia(h,b.current);c.spfPrefetched=!!h&&h.type=="prefetch";c.spfCached=!!h;if(h){a=D(Ca,null,a,b,c,h.key,h.response);b=window._spf_state=window._spf_state||{};var m=parseInt(b.uid,10)||0;m++;b=b.uid=m;T[b]=a;ka?window.postMessage("spf:"+b,"*"):
window.setTimeout(D(ha,null,b),0);a=null}else{h={};if(f=K["request-headers"])for(m in f)k=f[m],h[m]=k==null?"":String(k);if(b.headers)for(m in b.headers)k=b.headers[m],h[m]=k==null?"":String(k);b.B!=null&&(h["X-SPF-Referer"]=b.B);b.current!=null&&(h["X-SPF-Previous"]=b.current);if(m=K["advanced-header-identifier"])h["X-SPF-Request"]=m.replace("__type__",b.type),h.Accept="application/json";m=new Ja;f=D(Ga,null,a,b,c,m);a={headers:h,C:K["request-timeout"],u:D(Ea,null,a,m),l:D(Fa,null,a,b,c,m),s:f,A:f};
b.withCredentials&&(a.withCredentials=b.withCredentials);K["advanced-response-type-json"]&&(a.responseType="json");a=b.method=="POST"?Ba("POST",d,b.D,a):Ba("GET",d,null,a)}return a}},n=this;n.spf=n.spf||{};var Oa=n.spf,Z;for(Z in Na)Oa[Z]=Na[Z];}).call(this);
